### ISSUE TITLE
about overlay nag component

### ISSUE THREAD

**Issue by 332lfgb6** [fomantic/Fomantic-UI-Docs#400]
# Bug Report
Click the close icon,overlay nag does not disappear, In other cases, clicking the close icon makes the nag disappear immediately

## Steps 
1. click close icon

## Expected result
clicking the close icon makes the nag disappear immediately

## Actual result
Click the close icon,nag does not disappear

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/51245335/201171203-75e3ea0d-832f-41c5-98d0-39d6f445e7ac.png)

## Version
2.9.0

**Comment by lubber-de** [comment]
Fixed by #401

**Comment by 332lfgb6** [comment]
> Fixed by #401

I read your commit, but I still can't use it😁。。
Another problem is that other overlay nag is hidden by default and must be displayed through js, but this overlay nag is displayed by default.
```html
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.1/dist/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/fomantic-ui@2.9.0/dist/semantic.min.css" />
<script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.9.0/dist/semantic.min.js"></script>

<div class="ui segment">
  <div class="ui overlay nag">
    <div class="title">Welcome to the nag module</div>
    <div>Look, I am a top overlay nag!</div>
    <i class="close icon"></i>
  </div>
  <p>12345678</p>
  <p>12345678</p>
  <p>12345678</p>
  <p>12345678</p>
  <p>12345678</p>
  <p>12345678</p>
  <p>12345678</p>
</div>
<!--I don't even need to write this code-->
<!--I don't even need to write this code-->
<!--I don't even need to write this code-->
<button id="btn">button</button>
<script>
  $(document).ready(() => {
    $('#btn').click(() => {
      $('.ui.nag').nag()
    })
  })
</script>

```
### How should I change the code?
![image](https://user-images.githubusercontent.com/51245335/201346523-19261400-12c3-41bb-8c72-2b3ecf4d6b98.png)

**Comment by lubber-de** [comment]
Thanks, that is now fixed by https://github.com/fomantic/Fomantic-UI/pull/2552
